### ISSUE TITLE
Adding JsonIgnore attributes causes issues

### ISSUE THREAD

**Issue by mmedic** [jellyfin/jellyfin-sdk-csharp#26]
When trying to restrict libraries for a user, if user has All Libraries enabled in Jellyfin, when setting `EnableAllFolders` to `false`, it causes the property to not be written in the request body and `EnableAllFolders` never gets disabled.

```
[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
public bool EnableAllFolders { get; set; }
```

`JsonIgnore` should be removed from above.

**Comment by crobibero** [comment]
Are you using v2022.06.11?
If so I highly recommend moving to the unstable package as the sdk has had major work done

**Comment by crobibero** [comment]
Closing as the generation library has changed
